### ISSUE TITLE
`make world` fails at running sphinx

### ISSUE THREAD

**Issue by highPriestLOL** [websauna/websauna#126]
At [`make world`](https://websauna.org/docs/narrative/contributing/develop.html#building-docs) step of develop setup.

Sphinx version: 1.6.1
Python version: 3.5.2 (CPython)
Docutils version: 0.13.1 release
Jinja2 version: 2.9.6
Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/opt/mapylons/websauna/websauna/venv/lib/python3.5/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/opt/mapylons/websauna/websauna/venv/lib/python3.5/site-packages/sphinx/application.py", line 195, in __init__
    self.setup_extension(extension)
  File "/opt/mapylons/websauna/websauna/venv/lib/python3.5/site-packages/sphinx/application.py", line 455, in setup_extension
    self.registry.load_extension(self, extname)
  File "/opt/mapylons/websauna/websauna/venv/lib/python3.5/site-packages/sphinx/registry.py", line 207, in load_extension
    metadata = mod.setup(app)
  File "/opt/mapylons/websauna/websauna/venv/lib/python3.5/site-packages/pyramid_autodoc/__init__.py", line 335, in setup
    if 'http' not in app.domains:
AttributeError: 'Sphinx' object has no attribute 'domains'

**Comment by ericof** [comment]
Due to this issue https://github.com/SurveyMonkey/pyramid_autodoc/issues/13

**Comment by ericof** [comment]
We removed the dependency on pyramid_autodoc, and not it works
