### ISSUE TITLE
Error with ws-create-user in production environment

### ISSUE THREAD

**Issue by mazz** [websauna/websauna#140]
`kjvrvg` is the name of the webapp, but the ws-create-user command appears to look for logs in the conf dir:
```
ws-create-user conf/production.ini user@yahoo.com mypass --admin
Traceback (most recent call last):
  File "/srv/pyramid/kjvrvg/venv/bin/ws-create-user", line 11, in <module>
    load_entry_point('websauna', 'console_scripts', 'ws-create-user')()
  File "/srv/pyramid/kjvrvg/venv/src/websauna/websauna/system/devop/scripts/createuser.py", line 65, in main
    request = init_websauna(config_uri)
  File "/srv/pyramid/kjvrvg/venv/src/websauna/websauna/system/devop/cmdline.py", line 89, in init_websauna
    setup_logging(config_uri)
  File "/srv/pyramid/kjvrvg/venv/src/websauna/websauna/system/devop/cmdline.py", line 28, in setup_logging
    return fileConfig(parser, defaults, disable_existing_loggers)
  File "/usr/lib/python3.5/logging/config.py", line 84, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/lib/python3.5/logging/config.py", line 148, in _install_handlers
    h = klass(*args)
  File "/usr/lib/python3.5/logging/__init__.py", line 1009, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.5/logging/__init__.py", line 1038, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/srv/pyramid/kjvrvg/kjvrvg/logs/websauna.log'
```

**Comment by ericof** [comment]
@mazz Could you, please, share your ini files? (sanitise any database connection string and secrets)
Also, which versions and how did you create your app?

**Comment by ooduor** [comment]
@mazz can you try running this command from one level above. As in `ws-create-user kjvrvg/conf/production.ini user@yahoo.com mypass --admin` I did encounter this sort of error initially when I got into websauna :)

**Comment by mazz** [comment]
Sorry I'm slow on follow-up to this, been busy with a lead-up to release. Will follow-up once things get a bit quieter.

**Comment by slav0nic** [comment]
`mkdir -p logs` will solve you problem, maybe will be fine add logs folder to default app template

**Comment by mazz** [comment]
I wasn't in the wrong dir, sorry about the noise.
