### ISSUE TITLE
Web shell issue on clean setup

### ISSUE THREAD

**Issue by Fazik** [websauna/websauna#143]
Hi,
I receiving next stack trace when trying to open shell in web on my user:
`
[23:43:02] [waitress service] Exception when serving /admin/models/user/puNWkjXkTACeZ8TRz34bcQ/shell
Traceback (most recent call last):
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid/router.py", line 233, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid/router.py", line 208, in invoke_subrequest
    response = handle_request(request)
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid_debugtoolbar/toolbar.py", line 212, in toolbar_tween
    return handler(request)
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 171, in tm_tween
    reraise(*exc_info)
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid_tm/compat.py", line 36, in reraise
    raise value
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 136, in tm_tween
    response = handler(request)
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/websauna/system/auth/tweens.py", line 27, in __call__
    response = self.handler(request)
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 351, in authdebug_view
    return view(context, request)
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 300, in secured_view
    return view(context, request)
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 512, in csrf_view
    return view(context, request)
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 409, in viewresult_to_response
    result = view(context, request)
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 137, in _class_view
    response = getattr(inst, attr)()
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/websauna/system/notebook/adminviews.py", line 23, in shell
    return launch_context_sensitive_shell(self.request, extra_script, extra_greeting)
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/websauna/system/notebook/views.py", line 72, in launch_context_sensitive_shell
    return launch_notebook(request, request.user.username, notebook_context=nb)
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid_notebook/views.py", line 178, in launch_notebook
    notebook_info = launch_on_demand(request, username, notebook_context)
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid_notebook/views.py", line 147, in launch_on_demand
    notebook_info, creates = manager.start_notebook_on_demand(username, notebook_context)
  File "/root/projects/cloudmigrate/venv/lib/python3.6/site-packages/pyramid_notebook/notebookmanager.py", line 203, in start_notebook_on_demand
    if "notebook_name" not in context:
TypeError: argument of type 'NoneType' is not iterable
`

**Comment by ericof** [comment]
@Fazik: Would you mind sharing the versions of:
* Websauna
* Pyramid
* pyramid_notebook

**Comment by Fazik** [comment]
Sure @ericof 

notebook (5.2.1)
websauna (1.0a4)
pyramid (1.8)
pyramid-notebook (0.2.1)

**Comment by Fazik** [comment]
Maybe someone can provide with definitely working set of needed packages, so I will be able to check if this some env specific issue or just not correct versions?

**Comment by ericof** [comment]
@Fazik Are you able to use the current development version?
`pip install -e "git+https://github.com/websauna/websauna.git@master#egg=websauna[celery,utils,notebook]"`

**Comment by Fazik** [comment]
@ericof 
Nope, the same error

**Comment by Fazik** [comment]
Tried to downgrade python to 3.5
Sadly, but this is not the root cause
`Traceback (most recent call last):
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid/tweens.py", line 12, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid/view.py", line 756, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/myproject/venv/lib/python3.5/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/root/myproject/venv/lib/python3.5/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/root/myproject/venv/lib/python3.5/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid_retry/__init__.py", line 134, in retry_policy
    return request.invoke_exception_view(reraise=True)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid/view.py", line 755, in invoke_exception_view
    reraise_(*exc_info)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid_retry/__init__.py", line 114, in retry_policy
    response = router.invoke_request(request)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid_debugtoolbar/toolbar.py", line 212, in toolbar_tween
    return handler(request)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid_tm/__init__.py", line 171, in tm_tween
    reraise(*exc_info)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid_tm/compat.py", line 36, in reraise
    raise value
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid_tm/__init__.py", line 136, in tm_tween
    response = handler(request)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/root/myproject/venv/src/websauna/websauna/system/auth/tweens.py", line 56, in __call__
    response = self.handler(request)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid/viewderivers.py", line 352, in authdebug_view
    return view(context, request)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid/viewderivers.py", line 301, in secured_view
    return view(context, request)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid/viewderivers.py", line 513, in csrf_view
    return view(context, request)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid/viewderivers.py", line 410, in viewresult_to_response
    result = view(context, request)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid/viewderivers.py", line 148, in _requestonly_view
    response = view(request)
  File "/root/myproject/venv/src/websauna/websauna/system/notebook/views.py", line 92, in admin_shell
    return launch_context_sensitive_shell(request)
  File "/root/myproject/venv/src/websauna/websauna/system/notebook/views.py", line 72, in launch_context_sensitive_shell
    return launch_notebook(request, request.user.username, notebook_context=nb)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid_notebook/views.py", line 178, in launch_notebook
    notebook_info = launch_on_demand(request, username, notebook_context)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid_notebook/views.py", line 147, in launch_on_demand
    notebook_info, creates = manager.start_notebook_on_demand(username, notebook_context)
  File "/root/myproject/venv/lib/python3.5/site-packages/pyramid_notebook/notebookmanager.py", line 203, in start_notebook_on_demand
    if "notebook_name" not in context:
TypeError: argument of type 'NoneType' is not iterable`

**Comment by ericof** [comment]
@Fazik As I could not replicate that on a clean install I need to ask you more info:
* What is the OS/version?
* Are you running development|production.ini?
* How was your app created?

**Comment by Fazik** [comment]
@ericof 
OS: tested on Centos 7 / FreeBSD 11
Development.ini
pcreate -t websauna_app myapp
I simply used steps described in "Getting started" in documentation

**Comment by Fazik** [comment]
@ericof 
Just setuped Ubuntu instance - no difference.
If you want I can create ssh access for you to this new instance.

**Comment by Fazik** [comment]
OK.
Found the root cause of this.
I was running ws-pserve under root and notebook's daemon did not like that.

**Comment by ericof** [comment]
@Fazik Thanks for the update. I will write it down on the docs about this issue
