### ISSUE TITLE
trouble with app testing: missing websauna.tests.fixtures

### ISSUE THREAD

**Issue by kgk** [websauna/websauna#166]
I created an app (suana_test) that is working and am trying to get the tests running.

```
pip install -e ".[test]"
py.test saunatest --ini saunatest/app/conf/test.ini
```

results in 

```
Traceback (most recent call last):
  File "/usr/bin/py.test", line 11, in <module>
    load_entry_point('pytest==3.0.6', 'console_scripts', 'pytest')()
  File "/usr/lib/python2.7/dist-packages/_pytest/config.py", line 47, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python2.7/dist-packages/_pytest/config.py", line 156, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/usr/lib/python2.7/dist-packages/_pytest/helpconfig.py", line 32, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 280, in get_result
    _reraise(*ex)  # noqa
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/usr/lib/python2.7/dist-packages/_pytest/config.py", line 923, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python2.7/dist-packages/_pytest/config.py", line 1080, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python2.7/dist-packages/_pytest/config.py", line 1041, in _preparse
    self.pluginmanager.consider_preparse(args)
  File "/usr/lib/python2.7/dist-packages/_pytest/config.py", line 386, in consider_preparse
    self.consider_pluginarg(opt2)
  File "/usr/lib/python2.7/dist-packages/_pytest/config.py", line 395, in consider_pluginarg
    self.import_plugin(arg)
  File "/usr/lib/python2.7/dist-packages/_pytest/config.py", line 433, in import_plugin
    raise new_exc
ImportError: Error importing plugin "websauna.tests.fixtures": No module named websauna.tests.fixtures
```

Suggestions welcome..

**Comment by ericof** [comment]
It seems you are using Python 2.7.
Could you, please try it with Python >=3.5.2?

**Comment by ericof** [comment]
@kgk Any update?

**Comment by ericof** [comment]
Closing after no updates
