### ISSUE TITLE
ModuleNotFoundError: No module named 'websauna.utils'

### ISSUE THREAD

**Issue by enkidulan** [websauna/websauna#174]
Created a new app with cookiecutter and got `ModuleNotFoundError` when were trying to run `ws-alembic`:

```
> ws-alembic -c myapp/conf/development.ini -x packages=all revision --auto -m "Adding blog content types"
Traceback (most recent call last):
  File "/home/enkidulan/projects/enkidulan.blog/env/bin/ws-alembic", line 7, in <module>
    from websauna.system.devop.scripts.alembic import main
  File "/home/enkidulan/projects/enkidulan.blog/env/lib64/python3.6/site-packages/websauna/system/__init__.py", line 27, in <module>
    from websauna.utils.autoevent import event_source
ModuleNotFoundError: No module named 'websauna.utils'
```
Have tried with pip 9 and 10: 
```
> pip -V
pip 10.0.0 from /home/enkidulan/projects/enkidulan.blog/env/lib64/python3.6/site-packages/pip (python 3.6)
> pip freeze | grep websauna
websauna==1.0a7
-e git+https://github.com/websauna/websauna.blog@c92573524fd5db4cdb29e24e230c8f56de16d84c#egg=websauna.blog

```

**Comment by enkidulan** [comment]
Closing in favor to https://github.com/websauna/websauna.blog/issues/6
