### ISSUE TITLE
notebook fails on startup: if "notebook_name" not in context: TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by kgk** [websauna/websauna#223]
Trying out websauna and interested in notebook functionality.

Tried install using pip install "websauna[celery,utils,notebook]" and from git with same result (after adjusting setup.py dependencies for redis). 

`Starting server in PID 1693.
Serving on http://0.0.0.0:6543
[16:40:40] [websauna.system.core.redis log_redis_statistics] Redis connection statistics - process: 1693, thread: waitress, created: 1, max: 16, in-use: 1, available: 0
[16:40:40] [websauna.system.core.session create_session] Skipped session creation for http://localhost:6543/viqi.bq06-static/theme.css
[16:40:40] [websauna.system.core.session create_session] Skipped session creation for http://localhost:6543/viqi.bq06-static/logo.png
[16:40:40] [websauna.system.core.redis log_redis_statistics] Redis connection statistics - process: 1693, thread: waitress, created: 1, max: 16, in-use: 1, available: 0
[16:40:40] [websauna.system.core.redis log_redis_statistics] Redis connection statistics - process: 1693, thread: waitress, created: 1, max: 16, in-use: 1, available: 0
[16:40:43] [websauna.system.core.redis log_redis_statistics] Redis connection statistics - process: 1693, thread: waitress, created: 1, max: 16, in-use: 1, available: 0
[16:40:48] [websauna.system.core.redis log_redis_statistics] Redis connection statistics - process: 1693, thread: waitress, created: 1, max: 16, in-use: 1, available: 0
[16:40:48] [websauna.system.core.redis log_redis_statistics] Redis connection statistics - process: 1693, thread: waitress, created: 1, max: 16, in-use: 1, available: 0
[16:40:52] [websauna.system.core.redis log_redis_statistics] Redis connection statistics - process: 1693, thread: waitress, created: 1, max: 16, in-use: 1, available: 0
User <class 'websauna.system.user.models.User'>
websauna.system.user.models
_sa_module_registry <sqlalchemy.ext.declarative.clsregistry._ModuleMarker object at 0x7f8fc4045938>
Group <class 'websauna.system.user.models.Group'>
websauna.system.user.models
Activation <class 'websauna.system.user.models.Activation'>
websauna.system.user.models
UserGroup <class 'websauna.system.user.models.UserGroup'>
websauna.system.user.models
{'greeting': '\n\nAvailable variables and functions:\n\n* **app** - The [WSGI application](http://docs.pylonsproject.org/docs/pyramid/en/latest/api/paster.html?highlight=wsgi%20application#pyramid.paster.get_app) object generated by bootstrapping.\n* **request** - A [pyramid.request.Request](http://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request) object implying the current request state for your script.\n* **root** - The resource [root](http://docs.pylonsproject.org/docs/pyramid/en/latest/glossary.html#term-root) of your Pyramid application. This is an object generated by the [root factory](http://docs.pylonsproject.org/docs/pyramid/en/latest/glossary.html#term-root-factory) configured in your application.\n* **registry** - The application [registry](http://docs.pylonsproject.org/docs/pyramid/en/latest/glossary.html#term-application-registry) of your Pyramid application.\n\n* **datetime** - Python [datetime module](https://docs.python.org/3.5/library/datetime.html)\n* **time** - Python [time module](https://docs.python.org/3.5/library/time.html)\n* **transaction** - Zope [transaction manager](http://zodb.readthedocs.org/en/latest/transactions.html), e.g. `transaction.commit()`\n\n* **sqlalchemy** - sqlachemy module\n* **dbsession** - SQLAlchemy database session\n* **now()** - UTC time as timezone aware datetime object\n* **initializer** - websauna.system.Initializer instance\n\n* **User** - websauna.system.user.models.User\n* **Group** - websauna.system.user.models.Group\n* **Activation** - websauna.system.user.models.Activation\n* **UserGroup** - websauna.system.user.models.UserGroup\n\n', 'startup': "\n\nfrom pkg_resources import load_entry_point\nfrom pyramid_notebook.utils import change_directory\n\n# We need to use this to trigger a proper namespaced package loading\n# due to different approaches between pip / easy_install / python setup.py develop\n# (it doesn't matter which entry point we load as long as it's from websauna package)\nentry_point  = load_entry_point('websauna', 'console_scripts', 'ws-shell')\n\nfrom websauna.system.devop.cmdline import init_websauna_script_env\n\n# Our development.ini, production.ini, etc.\nconfig_file = '/source/websauna/viqi.bq06/viqi/bq06/conf/development.ini'\n\nwith change_directory('/source/websauna/viqi.bq06'):\n    script_env = init_websauna_script_env(config_file)\n    globals().update(script_env)\n\n\nimport datetime\nimport time\nimport transaction\n\n\ndbsession = request.dbsession\nfrom websauna.utils.time import now\nimport sqlalchemy\n\nfrom websauna.system.user.models import User\nfrom websauna.system.user.models import Group\nfrom websauna.system.user.models import Activation\nfrom websauna.system.user.models import UserGroup\n\n", 'extra_template_paths': ['/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid_notebook/server/templates'], 'jinja_environment_options': {}, 'allow_origin': 'http://localhost:6543', 'notebook_path': '/notebook/', 'context_hash': -3578348869437886086}
[16:40:54] [waitress service] Exception while serving /notebook/admin-shell
Traceback (most recent call last):
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid/view.py", line 779, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/waitress/channel.py", line 356, in service
    task.service()
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/waitress/task.py", line 176, in service
    self.execute()
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/waitress/task.py", line 447, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid_retry/__init__.py", line 134, in retry_policy
    return request.invoke_exception_view(reraise=True)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid/view.py", line 778, in invoke_exception_view
    reraise_(*exc_info)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid_retry/__init__.py", line 114, in retry_policy
    response = router.invoke_request(request)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid_debugtoolbar/toolbar.py", line 222, in toolbar_tween
    return handler(request)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 171, in tm_tween
    reraise(*exc_info)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid_tm/compat.py", line 36, in reraise
    raise value
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 136, in tm_tween
    response = handler(request)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/source/websauna/websauna/websauna/system/auth/tweens.py", line 60, in __call__
    response = self.handler(request)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid/viewderivers.py", line 384, in authdebug_view
    return view(context, request)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid/viewderivers.py", line 325, in secured_view
    return view(context, request)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid/viewderivers.py", line 514, in csrf_view
    return view(context, request)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
    response = view(request)
  File "/source/websauna/websauna/websauna/system/notebook/views.py", line 99, in admin_shell
    return launch_context_sensitive_shell(request)
  File "/source/websauna/websauna/websauna/system/notebook/views.py", line 79, in launch_context_sensitive_shell
    return launch_notebook(request, request.user.username, notebook_context=nb)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid_notebook/views.py", line 181, in launch_notebook
    notebook_info = launch_on_demand(request, username, notebook_context)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid_notebook/views.py", line 151, in launch_on_demand
    notebook_info, creates = manager.start_notebook_on_demand(username, notebook_context)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/pyramid_notebook/notebookmanager.py", line 206, in start_notebook_on_demand
    if "notebook_name" not in context:
TypeError: argument of type 'NoneType' is not iterable
`

**Comment by kgk** [comment]
From the notebook log under /tmp/pyramid_notebbook


`cat notebook.stderr.log 
Starting notebook, daemon True
Starting with context {'greeting': '\n\nAvailable variables and functions:\n\n* **app** - The [WSGI application](http://docs.pylonsproject.org/docs/pyramid/en/latest/api/paster.html?highlight=wsgi%20application#pyramid.paster.get_app) object generated by bootstrapping.\n* **request** - A [pyramid.request.Request](http://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request) object implying the current request state for your script.\n* **root** - The resource [root](http://docs.pylonsproject.org/docs/pyramid/en/latest/glossary.html#term-root) of your Pyramid application. This is an object generated by the [root factory](http://docs.pylonsproject.org/docs/pyramid/en/latest/glossary.html#term-root-factory) configured in your application.\n* **registry** - The application [registry](http://docs.pylonsproject.org/docs/pyramid/en/latest/glossary.html#term-application-registry) of your Pyramid application.\n\n* **datetime** - Python [datetime module](https://docs.python.org/3.5/library/datetime.html)\n* **time** - Python [time module](https://docs.python.org/3.5/library/time.html)\n* **transaction** - Zope [transaction manager](http://zodb.readthedocs.org/en/latest/transactions.html), e.g. `transaction.commit()`\n\n* **sqlalchemy** - sqlachemy module\n* **dbsession** - SQLAlchemy database session\n* **now()** - UTC time as timezone aware datetime object\n* **initializer** - websauna.system.Initializer instance\n\n* **User** - websauna.system.user.models.User\n* **Group** - websauna.system.user.models.Group\n* **Activation** - websauna.system.user.models.Activation\n* **UserGroup** - websauna.system.user.models.UserGroup\n\n', 'startup': "\n\nfrom pkg_resources import load_entry_point\nfrom pyramid_notebook.utils import change_directory\n\n# We need to use this to trigger a proper namespaced package loading\n# due to different approaches between pip / easy_install / python setup.py develop\n# (it doesn't matter which entry point we load as long as it's from websauna package)\nentry_point  = load_entry_point('websauna', 'console_scripts', 'ws-shell')\n\nfrom websauna.system.devop.cmdline import init_websauna_script_env\n\n# Our development.ini, production.ini, etc.\nconfig_file = '/source/websauna/viqi.bq06/viqi/bq06/conf/development.ini'\n\nwith change_directory('/source/websauna/viqi.bq06'):\n    script_env = init_websauna_script_env(config_file)\n    globals().update(script_env)\n\n\nimport datetime\nimport time\nimport transaction\n\n\ndbsession = request.dbsession\nfrom websauna.utils.time import now\nimport sqlalchemy\n\nfrom websauna.system.user.models import User\nfrom websauna.system.user.models import Group\nfrom websauna.system.user.models import Activation\nfrom websauna.system.user.models import UserGroup\n\n", 'extra_template_paths': ['/source/websauna/pyramid_notebook/pyramid_notebook/server/templates'], 'jinja_environment_options': {}, 'allow_origin': 'http://localhost:6543', 'notebook_path': '/notebook/', 'context_hash': -3048566473195917825, 'http_port': 40008, 'websocket_url': 'ws://localhost:40008'}
Launching on localhost:40008, having context {'greeting': '\n\nAvailable variables and functions:\n\n* **app** - The [WSGI application](http://docs.pylonsproject.org/docs/pyramid/en/latest/api/paster.html?highlight=wsgi%20application#pyramid.paster.get_app) object generated by bootstrapping.\n* **request** - A [pyramid.request.Request](http://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request) object implying the current request state for your script.\n* **root** - The resource [root](http://docs.pylonsproject.org/docs/pyramid/en/latest/glossary.html#term-root) of your Pyramid application. This is an object generated by the [root factory](http://docs.pylonsproject.org/docs/pyramid/en/latest/glossary.html#term-root-factory) configured in your application.\n* **registry** - The application [registry](http://docs.pylonsproject.org/docs/pyramid/en/latest/glossary.html#term-application-registry) of your Pyramid application.\n\n* **datetime** - Python [datetime module](https://docs.python.org/3.5/library/datetime.html)\n* **time** - Python [time module](https://docs.python.org/3.5/library/time.html)\n* **transaction** - Zope [transaction manager](http://zodb.readthedocs.org/en/latest/transactions.html), e.g. `transaction.commit()`\n\n* **sqlalchemy** - sqlachemy module\n* **dbsession** - SQLAlchemy database session\n* **now()** - UTC time as timezone aware datetime object\n* **initializer** - websauna.system.Initializer instance\n\n* **User** - websauna.system.user.models.User\n* **Group** - websauna.system.user.models.Group\n* **Activation** - websauna.system.user.models.Activation\n* **UserGroup** - websauna.system.user.models.UserGroup\n\n', 'startup': "\n\nfrom pkg_resources import load_entry_point\nfrom pyramid_notebook.utils import change_directory\n\n# We need to use this to trigger a proper namespaced package loading\n# due to different approaches between pip / easy_install / python setup.py develop\n# (it doesn't matter which entry point we load as long as it's from websauna package)\nentry_point  = load_entry_point('websauna', 'console_scripts', 'ws-shell')\n\nfrom websauna.system.devop.cmdline import init_websauna_script_env\n\n# Our development.ini, production.ini, etc.\nconfig_file = '/source/websauna/viqi.bq06/viqi/bq06/conf/development.ini'\n\nwith change_directory('/source/websauna/viqi.bq06'):\n    script_env = init_websauna_script_env(config_file)\n    globals().update(script_env)\n\n\nimport datetime\nimport time\nimport transaction\n\n\ndbsession = request.dbsession\nfrom websauna.utils.time import now\nimport sqlalchemy\n\nfrom websauna.system.user.models import User\nfrom websauna.system.user.models import Group\nfrom websauna.system.user.models import Activation\nfrom websauna.system.user.models import UserGroup\n\n", 'extra_template_paths': ['/source/websauna/pyramid_notebook/pyramid_notebook/server/templates'], 'jinja_environment_options': {}, 'allow_origin': 'http://localhost:6543', 'notebook_path': '/notebook/', 'context_hash': -3048566473195917825, 'http_port': 40008, 'websocket_url': 'ws://localhost:40008', 'pid': 3079, 'kill_timeout': 1800, 'notebook_name': 'default-3048566473195917825.ipynb'}
Dropping startup script /tmp/pyramid_notebook/kris@viqi.org/.jupyter/profile_default/startup/startup.py
[TerminalIPythonApp] Config changed:
[TerminalIPythonApp] {'NotebookApp': {'port': 40008, 'open_browser': False, 'base_url': '/notebook/', 'allow_origin': 'http://localhost:6543', 'extra_template_paths': ['/tmp/pyramid_notebook/kris@viqi.org/.jupyter/custom'], 'password_required': False, 'password': '', 'token': '', 'websocket_url': 'ws://localhost:40008'}, 'Application': {'log_level': 10}}
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook` in the future
[D 21:00:44.416 NotebookApp] Config changed:
[D 21:00:44.416 NotebookApp] {'NotebookApp': {'port': 40008, 'open_browser': False, 'base_url': '/notebook/', 'allow_origin': 'http://localhost:6543', 'extra_template_paths': ['/tmp/pyramid_notebook/kris@viqi.org/.jupyter/custom'], 'password_required': False, 'password': '', 'token': '', 'websocket_url': 'ws://localhost:40008'}, 'Application': {'log_level': 10}}
[D 21:00:44.417 NotebookApp] Searching ['/tmp/pyramid_notebook/kris@viqi.org', '/tmp/pyramid_notebook/kris@viqi.org/.jupyter', '/home/bisque/.virtualenvs/bq06/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 21:00:44.418 NotebookApp] Looking for jupyter_config in /etc/jupyter
[D 21:00:44.418 NotebookApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 21:00:44.418 NotebookApp] Looking for jupyter_config in /home/bisque/.virtualenvs/bq06/etc/jupyter
[D 21:00:44.418 NotebookApp] Looking for jupyter_config in /tmp/pyramid_notebook/kris@viqi.org/.jupyter
[D 21:00:44.418 NotebookApp] Looking for jupyter_config in /tmp/pyramid_notebook/kris@viqi.org
[D 21:00:44.418 NotebookApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 21:00:44.418 NotebookApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 21:00:44.419 NotebookApp] Looking for jupyter_notebook_config in /home/bisque/.virtualenvs/bq06/etc/jupyter
[D 21:00:44.419 NotebookApp] Looking for jupyter_notebook_config in /tmp/pyramid_notebook/kris@viqi.org/.jupyter
[D 21:00:44.419 NotebookApp] Looking for jupyter_notebook_config in /tmp/pyramid_notebook/kris@viqi.org
[W 21:00:44.434 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
Traceback (most recent call last):
  File "/source/websauna/pyramid_notebook/pyramid_notebook/server/notebook_daemon.py", line 233, in _run_notebook
    IPython.start_ipython(argv=argv, config=config)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "</home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/decorator.py:decorator-gen-113>", line 2, in initialize
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 308, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "</home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/IPython/core/application.py", line 450, in initialize
    self.parse_command_line(argv)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 303, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "</home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/decorator.py:decorator-gen-4>", line 2, in parse_command_line
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/traitlets/config/application.py", line 514, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/IPython/core/application.py", line 243, in initialize_subcommand
    return super(BaseIPythonApplication, self).initialize_subcommand(subc, argv)
  File "</home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/decorator.py:decorator-gen-3>", line 2, in initialize_subcommand
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/traitlets/config/application.py", line 452, in initialize_subcommand
    self.subapp.initialize(argv)
  File "</home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/decorator.py:decorator-gen-117>", line 2, in initialize
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/notebook/notebookapp.py", line 1630, in initialize
    self.init_webapp()
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/notebook/notebookapp.py", line 1407, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/bisque/.virtualenvs/bq06/lib/python3.6/site-packages/tornado/netutil.py", line 174, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address
shutdown Exiting with message: [Errno 99] Cannot assign requested address: 1
`

**Comment by kgk** [comment]
Disabling ipv6 in /etc/hosts seems to resolve this issue.. still not sure why it was picked up.

#::1     localhost ip6-localhost ip6-loopback
