### ISSUE TITLE
ws-db-shell throws FileNotFoundError

### ISSUE THREAD

**Issue by kissgyorgy** [websauna/websauna#6]
```
$ ws-db-shell conf/development.ini
Connecting to Engine(postgresql://localhost/myapp)
Traceback (most recent call last):
  File "/Users/walkman/Learning/websauna/venv/bin/pgcli", line 9, in <module>
    load_entry_point('pgcli', 'console_scripts', 'pgcli')()
  File "/Users/walkman/Learning/websauna/venv/lib/python3.5/site-packages/click-6.3-py3.5.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/walkman/Learning/websauna/venv/lib/python3.5/site-packages/click-6.3-py3.5.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/walkman/Learning/websauna/venv/lib/python3.5/site-packages/click-6.3-py3.5.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/walkman/Learning/websauna/venv/lib/python3.5/site-packages/click-6.3-py3.5.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/walkman/Learning/websauna/venv/lib/python3.5/site-packages/pgcli-0.20.1-py3.5.egg/pgcli/main.py", line 569, in cli
    pgcli = PGCli(prompt_passwd, never_prompt, pgclirc_file=pgclirc)
  File "/Users/walkman/Learning/websauna/venv/lib/python3.5/site-packages/pgcli-0.20.1-py3.5.egg/pgcli/main.py", line 87, in __init__
    write_default_config(default_config, pgclirc_file)
  File "/Users/walkman/Learning/websauna/venv/lib/python3.5/site-packages/pgcli-0.20.1-py3.5.egg/pgcli/config.py", line 26, in write_default_config
    shutil.copyfile(source, destination)
  File "/Users/walkman/Learning/websauna/venv/lib/python3.5/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/walkman/.config/pgcli/config'
```

Do you have any idea?

I have heavy symlink usage in my home directory, this might cause the problem, but still should be able to start.

**Comment by miohtama** [comment]
Sorry for not seeing new tickets earlier!

Does `pgcli` command standalone, not through Websauna, work with you?

If not this might be an issue with upstream package.

If it works then I'll try to figure out how to repeat.

**Comment by kissgyorgy** [comment]
Ok, `pgcli` did not start, but after fixing it, now throws this:
```
Traceback (most recent call last):
  File "/Users/walkman/.virtualenvs/websa/bin/ws-db-shell", line 9, in <module>
    load_entry_point('websauna==0.0', 'console_scripts', 'ws-db-shell')()
  File "/Users/walkman/.virtualenvs/websa/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/walkman/.virtualenvs/websa/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "/Users/walkman/.virtualenvs/websa/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/Users/walkman/.virtualenvs/websa/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'websauna.system.devop.scripts'
```

**Comment by miohtama** [comment]
The module is there: https://github.com/websauna/websauna/tree/master/websauna/system/devop/scripts

Try import the module in question from the Python shell within virtualenv.

If it doesn't work then nuke your virtualenv and reinstall everything.

**Comment by miohtama** [comment]
Any more input on this?

**Comment by ericof** [comment]
Closing after no input
