### ISSUE TITLE
TypeError: IContainer.items return value

### ISSUE THREAD

**Issue by karantan** [websauna/websauna#87]
I think this is a bug. So in the interfaces we have `IContainer` interface that has `items` method which should return `Iterable[Tuple[str, ILocation]]` but when we test this in `sitemapsamples.SampleContainer` we expect `Iterable[Tuple]`.

code:
https://github.com/websauna/websauna/blob/master/websauna/system/core/interfaces.py#L70
tests:
https://github.com/websauna/websauna/blob/master/websauna/tests/sitemapsamples.py#L31

error:
```
Traceback (most recent call last):
  File "/Users/karantan/github/tmp/venv/bin/ws-create", line 11, in <module>
    load_entry_point('websauna', 'console_scripts', 'ws-create')()
  File "/Users/karantan/github/tmp/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/karantan/github/tmp/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2627, in load_entry_point
    return ep.load()
  File "/Users/karantan/github/tmp/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2287, in load
    return self.resolve()
  File "/Users/karantan/github/tmp/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2293, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/karantan/github/websauna/websauna/system/__init__.py", line 5, in <module>
    from websauna.system.mail.utils import create_mailer
  File "/Users/karantan/github/websauna/websauna/system/mail/__init__.py", line 13, in <module>
    from websauna.system.http import Request
  File "/Users/karantan/github/websauna/websauna/system/http/__init__.py", line 9, in <module>
    from websauna.system.admin.admin import Admin
  File "/Users/karantan/github/websauna/websauna/system/admin/admin.py", line 9, in <module>
    from websauna.system.core.root import Root
  File "/Users/karantan/github/websauna/websauna/system/core/root.py", line 2, in <module>
    from websauna.system.core.interfaces import IRoot
  File "/Users/karantan/github/websauna/websauna/system/core/interfaces.py", line 22, in <module>
    class IContainer(ILocation):
  File "/Users/karantan/github/websauna/websauna/system/core/interfaces.py", line 70, in IContainer
    def items() -> Iterable[Tuple[str, ILocation]]:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/typing.py", line 696, in __getitem__
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/typing.py", line 696, in <genexpr>
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/typing.py", line 299, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
TypeError: Tuple[t0, t1, ...]: each t must be a type. Got <InterfaceClass pyramid.interfaces.ILocation>.

```

Can someone check if this is truly a bug or am I doing something wrong.

**Comment by JanLikar** [comment]
I'm fixing this.
